#!/usr/bin/env python
"""
Generate some names.
"""
# requires python 2.7

import sys
from argparse import ArgumentParser

from lib.namegen import NameGen

def main():
    args = parse_args()
    generator = NameGen('./lib/namegen_lang.txt')
    sep = ', '
    if args.newline:
        sep = '\n'
    print sep.join([generator.gen_word() for _ in range(args.count)])

def parse_args():
    default_count=5
    epilog = 'Stay awesome, spacelings!'
    parser = ArgumentParser(description=__doc__, epilog=epilog)
    parser.add_argument( '-c', '--count', default=default_count, dest='count',
            type=int, help='How many names to generate. [default: %s]' %
            default_count)
    parser.add_argument( '-n', '--newline', default=False,
            dest='newline', action='store_true', help='Use newlines to make '
            'the output tall instead of wide.')
    return parser.parse_args()

if __name__ == "__main__":
    sys.exit(main())
