#!/bin/bash

# This cmd will rerun only tests that failed on the previous run
# side effect: the --with-id will create a .noseids file
# CMD="nosetests-3.4 --failed --with-id --exe --detailed-errors"

# Right now the test suit is small enough that just running the tests in
# parallel keeps things short enough to be usable.
# bonus side effect: no .noseids file or weird behaviour to worry about
CMD="nosetests-3.4 --exe --detailed-errors --processes=-1 "

# Alternative Interface:
# if [[ "$1" = "-f" ]] || [[ "$1" = "--fancy" ]]; then

if [[ $# -eq 0 ]]; then
    exec $CMD --verbosity=2 2>&1 | \
        sed -e '/ \.\.\. SKIP: base class/d' -e '/ \.\.\. ok/d' \
            -e 's/ \.\.\. S/\n    S/' -e '/UserWarning/d' -e '/WARNING/d' \
            -e '/warn/d'

    echo "Cleaning up after the tests..."
    find . -iname "*.pyc" -or -iname "*.pyo" -or -iname "__pycache__" \
        -exec rm -rf '{}' '+'
elif [[ $# -eq 1 ]]; then
    if [[ "${1}" == "--clean" ]] || [[ "${1}" == "-c" ]]; then
        echo "Cleaning up..."
        find . -iname "*.pyc" -or -iname "*.pyo" -or -iname "__pycache__" \
            -exec rm -rf '{}' '+'
    else
        exec $CMD $@
    fi
else
    exec $CMD $@
fi
