#!/usr/bin/env python
"""
A space game where the player manages a space fairing civilization and
battles various challenges in growing their empire.
"""
# requires python 2.7

import sys
from argparse import ArgumentParser

from lib.cmdline.engine import SpaceEngine
from lib.cmdline.interpreter import SpaceCmdInterpreter

def main():
    args = parse_args()
    engine = SpaceEngine(args.save_file)
    SpaceCmdInterpreter(engine).start()

def parse_args():
    epilog = 'Stay awesome, spacelings!'
    parser = ArgumentParser(description=__doc__,
                            epilog=epilog)
    parser.add_argument(
            '-s', '--save-file', default='save.space', dest='save_file',
            help='The persistant game save file.')
    return parser.parse_args()

if __name__ == "__main__":
    sys.exit(main())
