--- !ditz.rubyforge.org,2008-03-06/project 
name: space
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: space
- !ditz.rubyforge.org,2008-03-06/component 
  name: model
- !ditz.rubyforge.org,2008-03-06/component 
  name: front_end
- !ditz.rubyforge.org,2008-03-06/component 
  name: engine
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2015-06-03 10:03:51.243168 Z
    - Curtis Sand <curtis@curtissand.com>
    - created
    - Python 3 support and unit test coverage.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2015-06-03 10:04:19.569098 Z
    - Curtis Sand <curtis@curtissand.com>
    - created
    - Save State.
